name: T W Campbell Art Music Video Story
favicon: null
layout_spectrum: 0.95633
typography_spectrum: 0.23239
title: ' Art Music Video Story 1986 - Present'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060409'
    - '#ffffff'
    - '#1e01d7'
    - '#b8aba5'
    - '#7832d0'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
