name: T W Campbell Art Music Video Story
favicon: null
layout_spectrum: 1
typography_spectrum: 0.29061
title: ' Art Music Video Story 1986 - Present'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020204'
    - '#ffffff'
    - '#ffc80a'
    - '#c30006'
    - '#c18813'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
