name: Thomas W. Campbell Art Music Video Story
favicon: null
layout_spectrum: 0.8591428834479302
typography_spectrum: 0.30371245625428855
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.14456303394399583
  lightness: 0.5322297343518585
  saturation: 0.08469864982180297
  rhythmicContrast: 0.0400456206407398
purpose: []
