name: T W Campbell Art Music Video Story
favicon: null
layout_spectrum: 0.95633
typography_spectrum: 0.30371245625428855
title: Art 1986 - Present
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010000'
    - '#fff4b4'
    - '#fecc45'
    - '#cb7e00'
    - '#481b00'
  brandStrength: 0.14456303394399583
  lightness: 0.5322297343518585
  saturation: 0.08469864982180297
  rhythmicContrast: 0.0400456206407398
purpose: []
